name: The Wicklow Wolf
description: Fabricator of Custom-Made Solutions
avatar: https://github.com/thewicklowwolf.png

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: thewicklowwolf
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow:
  youtube: 
  googleplus:

disqus:
google_analytics:
url:
baseurl: ""

permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
